name = "clarinet_frontend"
version = "0.1.0"
target = "javascript"
description = "Clarinet imaging trials framework frontend"

[dependencies]
lustre = "~> 5.4"

gleam_json = "~> 3.0"
gleam_javascript = "~> 1.0"
gleam_stdlib = "~> 0.63"
gleam_http = "~> 4.3"
modem = "~> 2.1"
gleam_fetch = "~> 1.3"
formosh = { git = "git@github.com:radionest/gleam_formosh.git", ref = "main" }
plinth = "~> 0.7.2"
multipart_form = "~> 1.0"
[dev-dependencies]
gleeunit = "~> 1.4"

[javascript]
entry_point = "clarinet.gleam"
output = "build/dev/javascript/clarinet.mjs"
